export const CUSTOMERS: any[] = [
  { name: 'Lithium', email: 'Hydrogen@gmail.com', code: 1.0079, actions: 'H' },
  { name: 'Helium', email: 'Helium@gmail.com', code: 4.0026, actions: 'He' },
  { name: 'Liithium', email: 'Liithium@gmail.com', code: 6.941, actions: 'Li' },
  {
    name: 'Beryllium',
    email: 'Beryllium@gmail.com',
    code: 9.0122,
    actions: 'Be',
  },
  { name: 'Boron', email: 'Boron@gmail.com', code: 10.811, actions: 'B' },
  { name: 'Carbon', email: 'Carbon@gmail.com', code: 12.0107, actions: 'C' },
  {
    name: 'Nitrogen',
    email: 'Nitrogen@gmail.com',
    code: 14.0067,
    actions: 'N',
  },
  { name: 'Oxygen', email: 'Oxygen@gmail.com', code: 15.9994, actions: 'O' },
  {
    name: 'Fluorine',
    email: 'Fluorine@gmail.com',
    code: 18.9984,
    actions: 'F',
  },
  { name: 'Neon', email: 'Neon@gmail.com', code: 20.1797, actions: 'Ne' },
  { name: 'Sodium', email: 'Sodium@gmail.com', code: 22.9897, actions: 'Na' },
  {
    name: 'Magnesium',
    email: 'Magnesium@gmail.com',
    code: 24.305,
    actions: 'Mg',
  },
  {
    name: 'Aluminum',
    email: 'Aluminum@gmail.com',
    code: 26.9815,
    actions: 'Al',
  },
  { name: 'Silicon', email: 'Silicon@gmail.com', code: 28.0855, actions: 'Si' },
  {
    name: 'Phosphorus',
    email: 'Phosphorus@gmail.com',
    code: 30.9738,
    actions: 'P',
  },
  { name: 'Sulfur', email: 'Sulfur@gmail.com', code: 32.065, actions: 'S' },
  {
    name: 'Chlorine',
    email: 'Chlorine@gmail.com',
    code: 35.453,
    actions: 'Cl',
  },
  { name: 'Argon', email: 'Argon@gmail.com', code: 39.948, actions: 'Ar' },
  {
    name: 'Potassium',
    email: 'Potassium@gmail.com',
    code: 39.0983,
    actions: 'K',
  },
  { name: 'Calcium', email: 'Calcium@gmail.com', code: 40.078, actions: 'Ca' },
];
export const suppliers: any[] = [
  { name: 'Lithium', email: 'Hydrogen@gmail.com', code: 1.0079, actions: 'H' },
  { name: 'Helium', email: 'Helium@gmail.com', code: 4.0026, actions: 'He' },
  { name: 'Liithium', email: 'Liithium@gmail.com', code: 6.941, actions: 'Li' },
  {
    name: 'Beryllium',
    email: 'Beryllium@gmail.com',
    code: 9.0122,
    actions: 'Be',
  },
  { name: 'Boron', email: 'Boron@gmail.com', code: 10.811, actions: 'B' },
  { name: 'Carbon', email: 'Carbon@gmail.com', code: 12.0107, actions: 'C' },
  {
    name: 'Nitrogen',
    email: 'Nitrogen@gmail.com',
    code: 14.0067,
    actions: 'N',
  },
  { name: 'Oxygen', email: 'Oxygen@gmail.com', code: 15.9994, actions: 'O' },
  {
    name: 'Fluorine',
    email: 'Fluorine@gmail.com',
    code: 18.9984,
    actions: 'F',
  },
  { name: 'Neon', email: 'Neon@gmail.com', code: 20.1797, actions: 'Ne' },
  { name: 'Sodium', email: 'Sodium@gmail.com', code: 22.9897, actions: 'Na' },
  {
    name: 'Magnesium',
    email: 'Magnesium@gmail.com',
    code: 24.305,
    actions: 'Mg',
  },
  {
    name: 'Aluminum',
    email: 'Aluminum@gmail.com',
    code: 26.9815,
    actions: 'Al',
  },
  { name: 'Silicon', email: 'Silicon@gmail.com', code: 28.0855, actions: 'Si' },
  {
    name: 'Phosphorus',
    email: 'Phosphorus@gmail.com',
    code: 30.9738,
    actions: 'P',
  },
  { name: 'Sulfur', email: 'Sulfur@gmail.com', code: 32.065, actions: 'S' },
  {
    name: 'Chlorine',
    email: 'Chlorine@gmail.com',
    code: 35.453,
    actions: 'Cl',
  },
  { name: 'Argon', email: 'Argon@gmail.com', code: 39.948, actions: 'Ar' },
  {
    name: 'Potassium',
    email: 'Potassium@gmail.com',
    code: 39.0983,
    actions: 'K',
  },
  { name: 'Calcium', email: 'Calcium@gmail.com', code: 40.078, actions: 'Ca' },
];
export const itemsCategory: any[] = [
  {
    name: 'Lithium',
    description: 'Hydrogen@gmail.com',
    actions: 'H',
  },
  {
    name: 'Helium',
    description: 'Helium@gmail.com',
    actions: 'He',
  },
  {
    name: 'Liithium',
    description: 'Liithium@gmail.com',
    actions: 'Li',
  },
  {
    name: 'Beryllium',
    description: 'Beryllium@gmail.com',
    actions: 'Be',
  },
  { name: 'Boron', description: 'Boron@gmail.com', actions: 'B' },
  {
    name: 'Carbon',
    description: 'Carbon@gmail.com',
    actions: 'C',
  },
  {
    name: 'Nitrogen',
    description: 'Nitrogen@gmail.com',
    actions: 'N',
  },
  {
    name: 'Oxygen',
    description: 'Oxygen@gmail.com',
    actions: 'O',
  },
  {
    name: 'Fluorine',
    description: 'Fluorine@gmail.com',
    actions: 'F',
  },
  { name: 'Neon', description: 'Neon@gmail.com', code: 20.1797, actions: 'Ne' },
  {
    name: 'Sodium',
    description: 'Sodium@gmail.com',
    actions: 'Na',
  },
  {
    name: 'Magnesium',
    description: 'Magnesium@gmail.com',
    actions: 'Mg',
  },
  {
    name: 'Aluminum',
    description: 'Aluminum@gmail.com',
    actions: 'Al',
  },
  {
    name: 'Silicon',
    description: 'Silicon@gmail.com',
    actions: 'Si',
  },
  {
    name: 'Phosphorus',
    description: 'Phosphorus@gmail.com',
    actions: 'P',
  },
  {
    name: 'Sulfur',
    description: 'Sulfur@gmail.com',
    actions: 'S',
  },
  {
    name: 'Chlorine',
    description: 'Chlorine@gmail.com',
    actions: 'Cl',
  },
  {
    name: 'Argon',
    description: 'Argon@gmail.com',
    actions: 'Ar',
  },
  {
    name: 'Potassium',
    description: 'Potassium@gmail.com',
    actions: 'K',
  },
  { name: 'Calcium', email: 'Calcium@gmail.com', code: 40.078, actions: 'Ca' },
];
export const payments: any[] = [
  {
    name: 'Lithium',
    amount: 'Hydrogen@gmail.com',
    paymentDate: 1.0079,
    description: 1.0079,
    actions: 'H',
  },
  {
    name: 'Helium',
    amount: 'Helium@gmail.com',
    paymentDate: 4.0026,
    description: 4.0026,
    actions: 'He',
  },
  {
    name: 'Liithium',
    amount: 'Liithium@gmail.com',
    paymentDate: 6.941,
    description: 6.941,
    actions: 'Li',
  },
  {
    name: 'Beryllium',
    amount: 'Beryllium@gmail.com',
    paymentDate: 9.0122,
    description: 9.0122,
    actions: 'Be',
  },
  {
    name: 'Boron',
    amount: 'Boron@gmail.com',
    paymentDate: 10.811,
    description: 10.811,
    actions: 'B',
  },
  {
    name: 'Carbon',
    amount: 'Carbon@gmail.com',
    paymentDate: 12.0107,
    description: 12.0107,
    actions: 'C',
  },
  {
    name: 'Nitrogen',
    amount: 'Nitrogen@gmail.com',
    paymentDate: 14.0067,
    description: 14.0067,
    actions: 'N',
  },
  {
    name: 'Oxygen',
    amount: 'Oxygen@gmail.com',
    paymentDate: 15.9994,
    description: 15.9994,
    actions: 'O',
  },
  {
    name: 'Fluorine',
    amount: 'Fluorine@gmail.com',
    paymentDate: 18.9984,
    description: 18.9984,
    actions: 'F',
  },
  {
    name: 'Neon',
    amount: 'Neon@gmail.com',
    paymentDate: 20.1797,
    description: 20.1797,
    actions: 'Ne',
  },
  {
    name: 'Sodium',
    amount: 'Sodium@gmail.com',
    paymentDate: 22.9897,
    description: 22.9897,
    actions: 'Na',
  },
  {
    name: 'Magnesium',
    amount: 'Magnesium@gmail.com',
    paymentDate: 24.305,
    description: 24.305,
    actions: 'Mg',
  },
  {
    name: 'Aluminum',
    amount: 'Aluminum@gmail.com',
    paymentDate: 26.9815,
    description: 26.9815,
    actions: 'Al',
  },
  {
    name: 'Silicon',
    amount: 'Silicon@gmail.com',
    paymentDate: 28.0855,
    description: 28.0855,
    actions: 'Si',
  },
  {
    name: 'Phosphorus',
    amount: 'Phosphorus@gmail.com',
    paymentDate: 30.9738,
    description: 30.9738,
    actions: 'P',
  },
  {
    name: 'Sulfur',
    amount: 'Sulfur@gmail.com',
    paymentDate: 32.065,
    description: 32.065,
    actions: 'S',
  },
  {
    name: 'Chlorine',
    amount: 'Chlorine@gmail.com',
    paymentDate: 35.453,
    description: 35.453,
    actions: 'Cl',
  },
  {
    name: 'Argon',
    amount: 'Argon@gmail.com',
    paymentDate: 39.948,
    description: 39.948,
    actions: 'Ar',
  },
  {
    name: 'Potassium',
    amount: 'Potassium@gmail.com',
    paymentDate: 39.0983,
    description: 39.0983,
    actions: 'K',
  },
  { name: 'Calcium', email: 'Calcium@gmail.com', code: 40.078, actions: 'Ca' },
];
export const expenses: any[] = [
  {
    name: 'Lithium',
    containerNumber: 'Hydrogen@gmail.com',
    amount: 1.0079,
    expenseDate: 1.0079,
    actions: 'H',
  },
  {
    name: 'Helium',
    containerNumber: 'Helium@gmail.com',
    amount: 4.0026,
    expenseDate: 4.0026,
    actions: 'He',
  },
  {
    name: 'Liithium',
    containerNumber: 'Liithium@gmail.com',
    amount: 6.941,
    expenseDate: 6.941,
    actions: 'Li',
  },
  {
    name: 'Beryllium',
    containerNumber: 'Beryllium@gmail.com',
    amount: 9.0122,
    expenseDate: 9.0122,
    actions: 'Be',
  },
  {
    name: 'Boron',
    containerNumber: 'Boron@gmail.com',
    amount: 10.811,
    expenseDate: 10.811,
    actions: 'B',
  },
  {
    name: 'Carbon',
    containerNumber: 'Carbon@gmail.com',
    amount: 12.0107,
    expenseDate: 12.0107,
    actions: 'C',
  },
  {
    name: 'Nitrogen',
    containerNumber: 'Nitrogen@gmail.com',
    amount: 14.0067,
    expenseDate: 14.0067,
    actions: 'N',
  },
  {
    name: 'Oxygen',
    containerNumber: 'Oxygen@gmail.com',
    amount: 15.9994,
    expenseDate: 15.9994,
    actions: 'O',
  },
  {
    name: 'Fluorine',
    containerNumber: 'Fluorine@gmail.com',
    amount: 18.9984,
    expenseDate: 18.9984,
    actions: 'F',
  },
  {
    name: 'Neon',
    containerNumber: 'Neon@gmail.com',
    amount: 20.1797,
    expenseDate: 20.1797,
    actions: 'Ne',
  },
  {
    name: 'Sodium',
    containerNumber: 'Sodium@gmail.com',
    amount: 22.9897,
    expenseDate: 22.9897,
    actions: 'Na',
  },
  {
    name: 'Magnesium',
    containerNumber: 'Magnesium@gmail.com',
    amount: 24.305,
    expenseDate: 24.305,
    actions: 'Mg',
  },
  {
    name: 'Aluminum',
    containerNumber: 'Aluminum@gmail.com',
    amount: 26.9815,
    expenseDate: 26.9815,
    actions: 'Al',
  },
  {
    name: 'Silicon',
    containerNumber: 'Silicon@gmail.com',
    amount: 28.0855,
    expenseDate: 28.0855,
    actions: 'Si',
  },
  {
    name: 'Phosphorus',
    containerNumber: 'Phosphorus@gmail.com',
    amount: 30.9738,
    expenseDate: 30.9738,
    actions: 'P',
  },
  {
    name: 'Sulfur',
    containerNumber: 'Sulfur@gmail.com',
    amount: 32.065,
    expenseDate: 32.065,
    actions: 'S',
  },
  {
    name: 'Chlorine',
    containerNumber: 'Chlorine@gmail.com',
    amount: 35.453,
    expenseDate: 35.453,
    actions: 'Cl',
  },
  {
    name: 'Argon',
    containerNumber: 'Argon@gmail.com',
    amount: 39.948,
    expenseDate: 39.948,
    actions: 'Ar',
  },
  {
    name: 'Potassium',
    containerNumber: 'Potassium@gmail.com',
    amount: 39.0983,
    expenseDate: 39.0983,
    actions: 'K',
  },
  {
    name: 'Calcium',
    containerNumber: 'Calcium@gmail.com',
    amount: 40.078,
    expenseDate: 40.078,
    actions: 'Ca',
  },
];
export const transactions: any[] = [
  {
    name: 'Lithium',
    invoiceNumber: 'Hydrogen@gmail.com',
    supplierName: 'Hydrogen@gmail.com',
    transactionDate: 1.0079,
    actions: 'H',
  },
  {
    name: 'Helium',
    invoiceNumber: 'Helium@gmail.com',
    supplierName: 'Helium@gmail.com',
    transactionDate: 4.0026,
    actions: 'He',
  },
  {
    name: 'Liithium',
    invoiceNumber: 'Liithium@gmail.com',
    supplierName: 'Liithium@gmail.com',
    transactionDate: 6.941,
    actions: 'Li',
  },
  {
    name: 'Beryllium',
    invoiceNumber: 'Beryllium@gmail.com',
    supplierName: 'Beryllium@gmail.com',
    transactionDate: 9.0122,
    actions: 'Be',
  },
  {
    name: 'Boron',
    invoiceNumber: 'Boron@gmail.com',
    supplierName: 'Boron@gmail.com',
    transactionDate: 10.811,
    actions: 'B',
  },
  {
    name: 'Carbon',
    invoiceNumber: 'Carbon@gmail.com',
    supplierName: 'Carbon@gmail.com',
    transactionDate: 12.0107,
    actions: 'C',
  },
  {
    name: 'Nitrogen',
    invoiceNumber: 'Nitrogen@gmail.com',
    supplierName: 'Nitrogen@gmail.com',
    transactionDate: 14.0067,
    actions: 'N',
  },
  {
    name: 'Oxygen',
    invoiceNumber: 'Oxygen@gmail.com',
    supplierName: 'Oxygen@gmail.com',
    transactionDate: 15.9994,
    actions: 'O',
  },
  {
    name: 'Fluorine',
    invoiceNumber: 'Fluorine@gmail.com',
    supplierName: 'Fluorine@gmail.com',
    transactionDate: 18.9984,
    actions: 'F',
  },
  {
    name: 'Neon',
    invoiceNumber: 'Neon@gmail.com',
    supplierName: 'Neon@gmail.com',
    transactionDate: 20.1797,
    actions: 'Ne',
  },
  {
    name: 'Sodium',
    invoiceNumber: 'Sodium@gmail.com',
    supplierName: 'Sodium@gmail.com',
    transactionDate: 22.9897,
    actions: 'Na',
  },
  {
    name: 'Magnesium',
    invoiceNumber: 'Magnesium@gmail.com',
    supplierName: 'Magnesium@gmail.com',
    transactionDate: 24.305,
    actions: 'Mg',
  },
  {
    name: 'Aluminum',
    invoiceNumber: 'Aluminum@gmail.com',
    supplierName: 'Aluminum@gmail.com',
    transactionDate: 26.9815,
    actions: 'Al',
  },
  {
    name: 'Silicon',
    invoiceNumber: 'Silicon@gmail.com',
    supplierName: 'Silicon@gmail.com',
    transactionDate: 28.0855,
    actions: 'Si',
  },
  {
    name: 'Phosphorus',
    invoiceNumber: 'Phosphorus@gmail.com',
    supplierName: 'Phosphorus@gmail.com',
    transactionDate: 30.9738,
    actions: 'P',
  },
  {
    name: 'Sulfur',
    invoiceNumber: 'Sulfur@gmail.com',
    supplierName: 'Sulfur@gmail.com',
    transactionDate: 32.065,
    actions: 'S',
  },
  {
    name: 'Chlorine',
    invoiceNumber: 'Chlorine@gmail.com',
    supplierName: 'Chlorine@gmail.com',
    transactionDate: 35.453,
    actions: 'Cl',
  },
  {
    name: 'Argon',
    invoiceNumber: 'Argon@gmail.com',
    supplierName: 'Argon@gmail.com',
    transactionDate: 39.948,
    actions: 'Ar',
  },
  {
    name: 'Potassium',
    invoiceNumber: 'Potassium@gmail.com',
    supplierName: 'Potassium@gmail.com',
    transactionDate: 39.0983,
    actions: 'K',
  },
  {
    name: 'Calcium',
    invoiceNumber: 'Calcium@gmail.com',
    supplierName: 'Calcium@gmail.com',
    transactionDate: 40.078,
    actions: 'Ca',
  },
];
export const shippingData: any[] = [
  {
    name: 'Lithium',
    containerNumber: 'Hydrogen@gmail.com',
    contatierSequance: 1.0079,
    ShippingDate: 1.0079,
    actions: 'H',
  },
  {
    name: 'Helium',
    containerNumber: 'Helium@gmail.com',
    contatierSequance: 4.0026,
    ShippingDate: 4.0026,
    actions: 'He',
  },
  {
    name: 'Liithium',
    containerNumber: 'Liithium@gmail.com',
    contatierSequance: 6.941,
    ShippingDate: 6.941,
    actions: 'Li',
  },
  {
    name: 'Beryllium',
    containerNumber: 'Beryllium@gmail.com',
    contatierSequance: 9.0122,
    ShippingDate: 9.0122,
    actions: 'Be',
  },
  {
    name: 'Boron',
    containerNumber: 'Boron@gmail.com',
    contatierSequance: 10.811,
    ShippingDate: 10.811,
    actions: 'B',
  },
  {
    name: 'Carbon',
    containerNumber: 'Carbon@gmail.com',
    contatierSequance: 12.0107,
    ShippingDate: 12.0107,
    actions: 'C',
  },
  {
    name: 'Nitrogen',
    containerNumber: 'Nitrogen@gmail.com',
    contatierSequance: 14.0067,
    ShippingDate: 14.0067,
    actions: 'N',
  },
  {
    name: 'Oxygen',
    containerNumber: 'Oxygen@gmail.com',
    contatierSequance: 15.9994,
    ShippingDate: 15.9994,
    actions: 'O',
  },
  {
    name: 'Fluorine',
    containerNumber: 'Fluorine@gmail.com',
    contatierSequance: 18.9984,
    ShippingDate: 18.9984,
    actions: 'F',
  },
  {
    name: 'Neon',
    containerNumber: 'Neon@gmail.com',
    contatierSequance: 20.1797,
    ShippingDate: 20.1797,
    actions: 'Ne',
  },
  {
    name: 'Sodium',
    containerNumber: 'Sodium@gmail.com',
    contatierSequance: 22.9897,
    ShippingDate: 22.9897,
    actions: 'Na',
  },
  {
    name: 'Magnesium',
    containerNumber: 'Magnesium@gmail.com',
    contatierSequance: 24.305,
    ShippingDate: 24.305,
    actions: 'Mg',
  },
  {
    name: 'Aluminum',
    containerNumber: 'Aluminum@gmail.com',
    contatierSequance: 26.9815,
    ShippingDate: 26.9815,
    actions: 'Al',
  },
  {
    name: 'Silicon',
    containerNumber: 'Silicon@gmail.com',
    contatierSequance: 28.0855,
    ShippingDate: 28.0855,
    actions: 'Si',
  },
  {
    name: 'Phosphorus',
    containerNumber: 'Phosphorus@gmail.com',
    contatierSequance: 30.9738,
    ShippingDate: 30.9738,
    actions: 'P',
  },
  {
    name: 'Sulfur',
    containerNumber: 'Sulfur@gmail.com',
    contatierSequance: 32.065,
    ShippingDate: 32.065,
    actions: 'S',
  },
  {
    name: 'Chlorine',
    containerNumber: 'Chlorine@gmail.com',
    contatierSequance: 35.453,
    ShippingDate: 35.453,
    actions: 'Cl',
  },
  {
    name: 'Argon',
    containerNumber: 'Argon@gmail.com',
    contatierSequance: 39.948,
    ShippingDate: 39.948,
    actions: 'Ar',
  },
  {
    name: 'Potassium',
    containerNumber: 'Potassium@gmail.com',
    contatierSequance: 39.0983,
    ShippingDate: 39.0983,
    actions: 'K',
  },
  {
    name: 'Calcium',
    containerNumber: 'Calcium@gmail.com',
    contatierSequance: 40.078,
    ShippingDate: 40.078,
    actions: 'Ca',
  },
];
export const shipmantReport: any[] = [
  {
    item: 'Lithium',
    description: 'Hydrogen@gmail.com',
    boxQnt: 1.0079,
    itemQnt: 1.0079,
    price: 'H',
    totalPrice: 'H',
    totalCBM: 'H',
    totalWeight: 'H',
  },
  {
    item: 'Helium',
    description: 'Helium@gmail.com',
    boxQnt: 4.0026,
    itemQnt: 4.0026,
    price: 'He',
    totalPrice: 'He',
    totalCBM: 'He',
    totalWeight: 'He',
  },
  {
    item: 'Liithium',
    description: 'Liithium@gmail.com',
    boxQnt: 6.941,
    itemQnt: 6.941,
    price: 'Li',
    totalPrice: 'Li',
    totalCBM: 'Li',
    totalWeight: 'Li',
  },
  {
    item: 'Beryllium',
    description: 'Beryllium@gmail.com',
    boxQnt: 9.0122,
    itemQnt: 9.0122,
    price: 'Be',
    totalPrice: 'Be',
    totalCBM: 'Be',
    totalWeight: 'Be',
  },
  {
    item: 'Boron',
    description: 'Boron@gmail.com',
    boxQnt: 10.811,
    itemQnt: 10.811,
    price: 'B',
    totalPrice: 'B',
    totalCBM: 'B',
    totalWeight: 'B',
  },
  {
    item: 'Carbon',
    description: 'Carbon@gmail.com',
    boxQnt: 12.0107,
    itemQnt: 12.0107,
    price: 'C',
    totalPrice: 'C',
    totalCBM: 'C',
    totalWeight: 'C',
  },
  {
    item: 'Nitrogen',
    description: 'Nitrogen@gmail.com',
    boxQnt: 14.0067,
    itemQnt: 14.0067,
    price: 'N',
    totalPrice: 'N',
    totalCBM: 'N',
    totalWeight: 'N',
  },
  {
    item: 'Oxygen',
    description: 'Oxygen@gmail.com',
    boxQnt: 15.9994,
    itemQnt: 15.9994,
    price: 'O',
    totalPrice: 'O',
    totalCBM: 'O',
    totalWeight: 'O',
  },
  {
    item: 'Fluorine',
    description: 'Fluorine@gmail.com',
    boxQnt: 18.9984,
    itemQnt: 18.9984,
    price: 'F',
    totalPrice: 'F',
    totalCBM: 'F',
    totalWeight: 'F',
  },
  {
    item: 'Neon',
    description: 'Neon@gmail.com',
    boxQnt: 20.1797,
    itemQnt: 20.1797,
    price: 'Ne',
    totalPrice: 'Ne',
    totalCBM: 'Ne',
    totalWeight: 'Ne',
  },
  {
    item: 'Sodium',
    description: 'Sodium@gmail.com',
    boxQnt: 22.9897,
    itemQnt: 22.9897,
    price: 'Na',
    totalPrice: 'Na',
    totalCBM: 'Na',
    totalWeight: 'Na',
  },
  {
    item: 'Magnesium',
    description: 'Magnesium@gmail.com',
    boxQnt: 24.305,
    itemQnt: 24.305,
    price: 'Mg',
    totalPrice: 'Mg',
    totalCBM: 'Mg',
    totalWeight: 'Mg',
  },
  {
    item: 'Aluminum',
    description: 'Aluminum@gmail.com',
    boxQnt: 26.9815,
    itemQnt: 26.9815,
    price: 'Al',
    totalPrice: 'Al',
    totalCBM: 'Al',
    totalWeight: 'Al',
  },
  {
    item: 'Silicon',
    description: 'Silicon@gmail.com',
    boxQnt: 28.0855,
    itemQnt: 28.0855,
    price: 'Si',
    totalPrice: 'Si',
    totalCBM: 'Si',
    totalWeight: 'Si',
  },
  {
    item: 'Phosphorus',
    description: 'Phosphorus@gmail.com',
    boxQnt: 30.9738,
    itemQnt: 30.9738,
    price: 'P',
    totalPrice: 'P',
    totalCBM: 'P',
    totalWeight: 'P',
  },
  {
    item: 'Sulfur',
    description: 'Sulfur@gmail.com',
    boxQnt: 32.065,
    itemQnt: 32.065,
    price: 'S',
    totalPrice: 'S',
    totalCBM: 'S',
    totalWeight: 'S',
  },
  {
    item: 'Chlorine',
    description: 'Chlorine@gmail.com',
    boxQnt: 35.453,
    itemQnt: 35.453,
    price: 'Cl',
    totalPrice: 'Cl',
    totalCBM: 'Cl',
    totalWeight: 'Cl',
  },
  {
    item: 'Argon',
    description: 'Argon@gmail.com',
    boxQnt: 39.948,
    itemQnt: 39.948,
    price: 'Ar',
    totalPrice: 'Ar',
    totalCBM: 'Ar',
    totalWeight: 'Ar',
  },
  {
    item: 'Potassium',
    description: 'Potassium@gmail.com',
    boxQnt: 39.0983,
    itemQnt: 39.0983,
    price: 'K',
    totalPrice: 'K',
    totalCBM: 'K',
    totalWeight: 'K',
  },
  {
    item: 'Calcium',
    description: 'Calcium@gmail.com',
    boxQnt: 40.078,
    itemQnt: 40.078,
    price: 'Ca',
    totalPrice: 'Ca',
    totalCBM: 'Ca',
    totalWeight: 'Ca',
  },
];
export const totalPayments: any[] = [
  {
    customer_code: 'Lithium',
    customer_name: 'Hydrogen@gmail.com',
    amount: 1.0079,
    date: 1.0079,
  },
  {
    customer_code: 'Helium',
    customer_name: 'Helium@gmail.com',
    amount: 4.0026,
    date: 4.0026,
  },
  {
    customer_code: 'Liithium',
    customer_name: 'Liithium@gmail.com',
    amount: 6.941,
    date: 6.941,
  },
  {
    customer_code: 'Beryllium',
    customer_name: 'Beryllium@gmail.com',
    amount: 9.0122,
    date: 9.0122,
  },
  {
    customer_code: 'Boron',
    customer_name: 'Boron@gmail.com',
    amount: 10.811,
    date: 10.811,
  },
  {
    customer_code: 'Carbon',
    customer_name: 'Carbon@gmail.com',
    amount: 12.0107,
    date: 12.0107,
  },
  {
    customer_code: 'Nitrogen',
    customer_name: 'Nitrogen@gmail.com',
    amount: 14.0067,
    date: 14.0067,
  },
  {
    customer_code: 'Oxygen',
    customer_name: 'Oxygen@gmail.com',
    amount: 15.9994,
    date: 15.9994,
  },
  {
    customer_code: 'Fluorine',
    customer_name: 'Fluorine@gmail.com',
    amount: 18.9984,
    date: 18.9984,
  },
  {
    customer_code: 'Neon',
    customer_name: 'Neon@gmail.com',
    amount: 20.1797,
    date: 20.1797,
  },
  {
    customer_code: 'Sodium',
    customer_name: 'Sodium@gmail.com',
    amount: 22.9897,
    date: 22.9897,
  },
  {
    customer_code: 'Magnesium',
    customer_name: 'Magnesium@gmail.com',
    amount: 24.305,
    date: 24.305,
  },
  {
    customer_code: 'Aluminum',
    customer_name: 'Aluminum@gmail.com',
    amount: 26.9815,
    date: 26.9815,
  },
  {
    customer_code: 'Silicon',
    customer_name: 'Silicon@gmail.com',
    amount: 28.0855,
    date: 28.0855,
  },
  {
    customer_code: 'Phosphorus',
    customer_name: 'Phosphorus@gmail.com',
    amount: 30.9738,
    date: 30.9738,
  },
  {
    customer_code: 'Sulfur',
    customer_name: 'Sulfur@gmail.com',
    amount: 32.065,
    date: 32.065,
  },
  {
    customer_code: 'Chlorine',
    customer_name: 'Chlorine@gmail.com',
    amount: 35.453,
    date: 35.453,
  },
  {
    customer_code: 'Argon',
    customer_name: 'Argon@gmail.com',
    amount: 39.948,
    date: 39.948,
  },
  {
    customer_code: 'Potassium',
    customer_name: 'Potassium@gmail.com',
    amount: 39.0983,
    date: 39.0983,
  },
  {
    customer_code: 'Calcium',
    customer_name: 'Calcium@gmail.com',
    amount: 40.078,
    date: 40.078,
  },
];
export const totalBalance: any[] = [
  {
    store_number: 'Lithium',
    total_invoice: 'Hydrogen@gmail.com',
    paid: 1.0079,
    remains: 1.0079,
  },
  {
    store_number: 'Helium',
    total_invoice: 'Helium@gmail.com',
    paid: 4.0026,
    remains: 4.0026,
  },
  {
    store_number: 'Liithium',
    total_invoice: 'Liithium@gmail.com',
    paid: 6.941,
    remains: 6.941,
  },
  {
    store_number: 'Beryllium',
    total_invoice: 'Beryllium@gmail.com',
    paid: 9.0122,
    remains: 9.0122,
  },
  {
    store_number: 'Boron',
    total_invoice: 'Boron@gmail.com',
    paid: 10.811,
    remains: 10.811,
  },
  {
    store_number: 'Carbon',
    total_invoice: 'Carbon@gmail.com',
    paid: 12.0107,
    remains: 12.0107,
  },
  {
    store_number: 'Nitrogen',
    total_invoice: 'Nitrogen@gmail.com',
    paid: 14.0067,
    remains: 14.0067,
  },
  {
    store_number: 'Oxygen',
    total_invoice: 'Oxygen@gmail.com',
    paid: 15.9994,
    remains: 15.9994,
  },
  {
    store_number: 'Fluorine',
    total_invoice: 'Fluorine@gmail.com',
    paid: 18.9984,
    remains: 18.9984,
  },
  {
    store_number: 'Neon',
    total_invoice: 'Neon@gmail.com',
    paid: 20.1797,
    remains: 20.1797,
  },
  {
    store_number: 'Sodium',
    total_invoice: 'Sodium@gmail.com',
    paid: 22.9897,
    remains: 22.9897,
  },
  {
    store_number: 'Magnesium',
    total_invoice: 'Magnesium@gmail.com',
    paid: 24.305,
    remains: 24.305,
  },
  {
    store_number: 'Aluminum',
    total_invoice: 'Aluminum@gmail.com',
    paid: 26.9815,
    remains: 26.9815,
  },
  {
    store_number: 'Silicon',
    total_invoice: 'Silicon@gmail.com',
    paid: 28.0855,
    remains: 28.0855,
  },
  {
    store_number: 'Phosphorus',
    total_invoice: 'Phosphorus@gmail.com',
    paid: 30.9738,
    remains: 30.9738,
  },
  {
    store_number: 'Sulfur',
    total_invoice: 'Sulfur@gmail.com',
    paid: 32.065,
    remains: 32.065,
  },
  {
    store_number: 'Chlorine',
    total_invoice: 'Chlorine@gmail.com',
    paid: 35.453,
    remains: 35.453,
  },
  {
    store_number: 'Argon',
    total_invoice: 'Argon@gmail.com',
    paid: 39.948,
    remains: 39.948,
  },
  {
    store_number: 'Potassium',
    total_invoice: 'Potassium@gmail.com',
    paid: 39.0983,
    remains: 39.0983,
  },
  {
    store_number: 'Calcium',
    total_invoice: 'Calcium@gmail.com',
    paid: 40.078,
    remains: 40.078,
  },
];
export const totalExpenses: any[] = [
  {
    customer_code: 'Lithium',
    customer_name: 'Hydrogen@gmail.com',
    amount: 1.0079,
    date: 1.0079,
  },
  {
    customer_code: 'Helium',
    customer_name: 'Helium@gmail.com',
    amount: 4.0026,
    date: 4.0026,
  },
  {
    customer_code: 'Liithium',
    customer_name: 'Liithium@gmail.com',
    amount: 6.941,
    date: 6.941,
  },
  {
    customer_code: 'Beryllium',
    customer_name: 'Beryllium@gmail.com',
    amount: 9.0122,
    date: 9.0122,
  },
  {
    customer_code: 'Boron',
    customer_name: 'Boron@gmail.com',
    amount: 10.811,
    date: 10.811,
  },
  {
    customer_code: 'Carbon',
    customer_name: 'Carbon@gmail.com',
    amount: 12.0107,
    date: 12.0107,
  },
  {
    customer_code: 'Nitrogen',
    customer_name: 'Nitrogen@gmail.com',
    amount: 14.0067,
    date: 14.0067,
  },
  {
    customer_code: 'Oxygen',
    customer_name: 'Oxygen@gmail.com',
    amount: 15.9994,
    date: 15.9994,
  },
  {
    customer_code: 'Fluorine',
    customer_name: 'Fluorine@gmail.com',
    amount: 18.9984,
    date: 18.9984,
  },
  {
    customer_code: 'Neon',
    customer_name: 'Neon@gmail.com',
    amount: 20.1797,
    date: 20.1797,
  },
  {
    customer_code: 'Sodium',
    customer_name: 'Sodium@gmail.com',
    amount: 22.9897,
    date: 22.9897,
  },
  {
    customer_code: 'Magnesium',
    customer_name: 'Magnesium@gmail.com',
    amount: 24.305,
    date: 24.305,
  },
  {
    customer_code: 'Aluminum',
    customer_name: 'Aluminum@gmail.com',
    amount: 26.9815,
    date: 26.9815,
  },
  {
    customer_code: 'Silicon',
    customer_name: 'Silicon@gmail.com',
    amount: 28.0855,
    date: 28.0855,
  },
  {
    customer_code: 'Phosphorus',
    customer_name: 'Phosphorus@gmail.com',
    amount: 30.9738,
    date: 30.9738,
  },
  {
    customer_code: 'Sulfur',
    customer_name: 'Sulfur@gmail.com',
    amount: 32.065,
    date: 32.065,
  },
  {
    customer_code: 'Chlorine',
    customer_name: 'Chlorine@gmail.com',
    amount: 35.453,
    date: 35.453,
  },
  {
    customer_code: 'Argon',
    customer_name: 'Argon@gmail.com',
    amount: 39.948,
    date: 39.948,
  },
  {
    customer_code: 'Potassium',
    customer_name: 'Potassium@gmail.com',
    amount: 39.0983,
    date: 39.0983,
  },
  {
    customer_code: 'Calcium',
    customer_name: 'Calcium@gmail.com',
    amount: 40.078,
    date: 40.078,
  },
];
export const totalPaids: any[] = [
  {
    invoice_number: 'Lithium',
    supplier_name: 'Hydrogen@gmail.com',
    supplier_store: 1.0079,
    customer_name: 1.0079,
    customer_code: 'H',
    amount: 'H',
    date: 'H',
  },
  {
    invoice_number: 'Helium',
    supplier_name: 'Helium@gmail.com',
    supplier_store: 4.0026,
    customer_name: 4.0026,
    customer_code: 'He',
    amount: 'He',
    date: 'He',
  },
  {
    invoice_number: 'Liithium',
    supplier_name: 'Liithium@gmail.com',
    supplier_store: 6.941,
    customer_name: 6.941,
    customer_code: 'Li',
    amount: 'Li',
    date: 'Li',
  },
  {
    invoice_number: 'Beryllium',
    supplier_name: 'Beryllium@gmail.com',
    supplier_store: 9.0122,
    customer_name: 9.0122,
    customer_code: 'Be',
    amount: 'Be',
    date: 'Be',
  },
  {
    invoice_number: 'Boron',
    supplier_name: 'Boron@gmail.com',
    supplier_store: 10.811,
    customer_name: 10.811,
    customer_code: 'B',
    amount: 'B',
    date: 'B',
  },
  {
    invoice_number: 'Carbon',
    supplier_name: 'Carbon@gmail.com',
    supplier_store: 12.0107,
    customer_name: 12.0107,
    customer_code: 'C',
    amount: 'C',
    date: 'C',
  },
  {
    invoice_number: 'Nitrogen',
    supplier_name: 'Nitrogen@gmail.com',
    supplier_store: 14.0067,
    customer_name: 14.0067,
    customer_code: 'N',
    amount: 'N',
    date: 'N',
  },
  {
    invoice_number: 'Oxygen',
    supplier_name: 'Oxygen@gmail.com',
    supplier_store: 15.9994,
    customer_name: 15.9994,
    customer_code: 'O',
    amount: 'O',
    date: 'O',
  },
  {
    invoice_number: 'Fluorine',
    supplier_name: 'Fluorine@gmail.com',
    supplier_store: 18.9984,
    customer_name: 18.9984,
    customer_code: 'F',
    amount: 'F',
    date: 'F',
  },
  {
    invoice_number: 'Neon',
    supplier_name: 'Neon@gmail.com',
    supplier_store: 20.1797,
    customer_name: 20.1797,
    customer_code: 'Ne',
    amount: 'Ne',
    date: 'Ne',
  },
  {
    invoice_number: 'Sodium',
    supplier_name: 'Sodium@gmail.com',
    supplier_store: 22.9897,
    customer_name: 22.9897,
    customer_code: 'Na',
    amount: 'Na',
    date: 'Na',
  },
  {
    invoice_number: 'Magnesium',
    supplier_name: 'Magnesium@gmail.com',
    supplier_store: 24.305,
    customer_name: 24.305,
    customer_code: 'Mg',
    amount: 'Mg',
    date: 'Mg',
  },
  {
    invoice_number: 'Aluminum',
    supplier_name: 'Aluminum@gmail.com',
    supplier_store: 26.9815,
    customer_name: 26.9815,
    customer_code: 'Al',
    amount: 'Al',
    date: 'Al',
  },
  {
    invoice_number: 'Silicon',
    supplier_name: 'Silicon@gmail.com',
    supplier_store: 28.0855,
    customer_name: 28.0855,
    customer_code: 'Si',
    amount: 'Si',
    date: 'Si',
  },
  {
    invoice_number: 'Phosphorus',
    supplier_name: 'Phosphorus@gmail.com',
    supplier_store: 30.9738,
    customer_name: 30.9738,
    customer_code: 'P',
    amount: 'P',
    date: 'P',
  },
  {
    invoice_number: 'Sulfur',
    supplier_name: 'Sulfur@gmail.com',
    supplier_store: 32.065,
    customer_name: 32.065,
    customer_code: 'S',
    amount: 'S',
    date: 'S',
  },
  {
    invoice_number: 'Chlorine',
    supplier_name: 'Chlorine@gmail.com',
    supplier_store: 35.453,
    customer_name: 35.453,
    customer_code: 'Cl',
    amount: 'Cl',
    date: 'Cl',
  },
  {
    invoice_number: 'Argon',
    supplier_name: 'Argon@gmail.com',
    supplier_store: 39.948,
    customer_name: 39.948,
    customer_code: 'Ar',
    amount: 'Ar',
    date: 'Ar',
  },
  {
    invoice_number: 'Potassium',
    supplier_name: 'Potassium@gmail.com',
    supplier_store: 39.0983,
    customer_name: 39.0983,
    customer_code: 'K',
    amount: 'K',
    date: 'K',
  },
  {
    invoice_number: 'Calcium',
    supplier_name: 'Calcium@gmail.com',
    supplier_store: 40.078,
    customer_name: 40.078,
    customer_code: 'Ca',
    amount: 'Ca',
    date: 'Ca',
  },
];
export const officeBalance: any[] = [
  {
    customer_code: 'Lithium',
    customer_name: 'Hydrogen@gmail.com',
    total_expenses: 1.0079,
    total_paids: 1.0079,
    balance: 'H',
  },
  {
    customer_code: 'Helium',
    customer_name: 'Helium@gmail.com',
    total_expenses: 4.0026,
    total_paids: 4.0026,
    balance: 'He',
  },
  {
    customer_code: 'Liithium',
    customer_name: 'Liithium@gmail.com',
    total_expenses: 6.941,
    total_paids: 6.941,
    balance: 'Li',
  },
  {
    customer_code: 'Beryllium',
    customer_name: 'Beryllium@gmail.com',
    total_expenses: 9.0122,
    total_paids: 9.0122,
    balance: 'Be',
  },
  {
    customer_code: 'Boron',
    customer_name: 'Boron@gmail.com',
    total_expenses: 10.811,
    total_paids: 10.811,
    balance: 'B',
  },
  {
    customer_code: 'Carbon',
    customer_name: 'Carbon@gmail.com',
    total_expenses: 12.0107,
    total_paids: 12.0107,
    balance: 'C',
  },
  {
    customer_code: 'Nitrogen',
    customer_name: 'Nitrogen@gmail.com',
    total_expenses: 14.0067,
    total_paids: 14.0067,
    balance: 'N',
  },
  {
    customer_code: 'Oxygen',
    customer_name: 'Oxygen@gmail.com',
    total_expenses: 15.9994,
    total_paids: 15.9994,
    balance: 'O',
  },
  {
    customer_code: 'Fluorine',
    customer_name: 'Fluorine@gmail.com',
    total_expenses: 18.9984,
    total_paids: 18.9984,
    balance: 'F',
  },
  {
    customer_code: 'Neon',
    customer_name: 'Neon@gmail.com',
    total_expenses: 20.1797,
    total_paids: 20.1797,
    balance: 'Ne',
  },
  {
    customer_code: 'Sodium',
    customer_name: 'Sodium@gmail.com',
    total_expenses: 22.9897,
    total_paids: 22.9897,
    balance: 'Na',
  },
  {
    customer_code: 'Magnesium',
    customer_name: 'Magnesium@gmail.com',
    total_expenses: 24.305,
    total_paids: 24.305,
    balance: 'Mg',
  },
  {
    customer_code: 'Aluminum',
    customer_name: 'Aluminum@gmail.com',
    total_expenses: 26.9815,
    total_paids: 26.9815,
    balance: 'Al',
  },
  {
    customer_code: 'Silicon',
    customer_name: 'Silicon@gmail.com',
    total_expenses: 28.0855,
    total_paids: 28.0855,
    balance: 'Si',
  },
  {
    customer_code: 'Phosphorus',
    customer_name: 'Phosphorus@gmail.com',
    total_expenses: 30.9738,
    total_paids: 30.9738,
    balance: 'P',
  },
  {
    customer_code: 'Sulfur',
    customer_name: 'Sulfur@gmail.com',
    total_expenses: 32.065,
    total_paids: 32.065,
    balance: 'S',
  },
  {
    customer_code: 'Chlorine',
    customer_name: 'Chlorine@gmail.com',
    total_expenses: 35.453,
    total_paids: 35.453,
    balance: 'Cl',
  },
  {
    customer_code: 'Argon',
    customer_name: 'Argon@gmail.com',
    total_expenses: 39.948,
    total_paids: 39.948,
    balance: 'Ar',
  },
  {
    customer_code: 'Potassium',
    customer_name: 'Potassium@gmail.com',
    total_expenses: 39.0983,
    total_paids: 39.0983,
    balance: 'K',
  },
  {
    customer_code: 'Calcium',
    customer_name: 'Calcium@gmail.com',
    total_expenses: 40.078,
    total_paids: 40.078,
    balance: 'Ca',
  },
];
export const invoices: any[] = [
  {
    invoiceNumber: 'Lithium',
    customer_name: 'Hydrogen@gmail.com',
    supplier: 1.0079,
    invoiceDate: 1.0079,
    totalAmount: 'H',
    netAmount: 'H',
    actions: 'H',
  },
  {
    invoiceNumber: 'Helium',
    customer_name: 'Helium@gmail.com',
    supplier: 4.0026,
    invoiceDate: 4.0026,
    totalAmount: 'He',
    netAmount: 'He',
    actions: 'He',
  },
  {
    invoiceNumber: 'Liithium',
    customer_name: 'Liithium@gmail.com',
    supplier: 6.941,
    invoiceDate: 6.941,
    totalAmount: 'Li',
    netAmount: 'Li',
    actions: 'Li',
  },
  {
    invoiceNumber: 'Beryllium',
    customer_name: 'Beryllium@gmail.com',
    supplier: 9.0122,
    invoiceDate: 9.0122,
    totalAmount: 'Be',
    netAmount: 'Be',
    actions: 'Be',
  },
  {
    invoiceNumber: 'Boron',
    customer_name: 'Boron@gmail.com',
    supplier: 10.811,
    invoiceDate: 10.811,
    totalAmount: 'B',
    netAmount: 'B',
    actions: 'B',
  },
  {
    invoiceNumber: 'Carbon',
    customer_name: 'Carbon@gmail.com',
    supplier: 12.0107,
    invoiceDate: 12.0107,
    totalAmount: 'C',
    netAmount: 'C',
    actions: 'C',
  },
  {
    invoiceNumber: 'Nitrogen',
    customer_name: 'Nitrogen@gmail.com',
    supplier: 14.0067,
    invoiceDate: 14.0067,
    totalAmount: 'N',
    netAmount: 'N',
    actions: 'N',
  },
  {
    invoiceNumber: 'Oxygen',
    customer_name: 'Oxygen@gmail.com',
    supplier: 15.9994,
    invoiceDate: 15.9994,
    totalAmount: 'O',
    netAmount: 'O',
    actions: 'O',
  },
  {
    invoiceNumber: 'Fluorine',
    customer_name: 'Fluorine@gmail.com',
    supplier: 18.9984,
    invoiceDate: 18.9984,
    totalAmount: 'F',
    netAmount: 'F',
    actions: 'F',
  },
  {
    invoiceNumber: 'Neon',
    customer_name: 'Neon@gmail.com',
    supplier: 20.1797,
    invoiceDate: 20.1797,
    totalAmount: 'Ne',
    netAmount: 'Ne',
    actions: 'Ne',
  },
  {
    invoiceNumber: 'Sodium',
    customer_name: 'Sodium@gmail.com',
    supplier: 22.9897,
    invoiceDate: 22.9897,
    totalAmount: 'Na',
    netAmount: 'Na',
    actions: 'Na',
  },
  {
    invoiceNumber: 'Magnesium',
    customer_name: 'Magnesium@gmail.com',
    supplier: 24.305,
    invoiceDate: 24.305,
    totalAmount: 'Mg',
    netAmount: 'Mg',
    actions: 'Mg',
  },
  {
    invoiceNumber: 'Aluminum',
    customer_name: 'Aluminum@gmail.com',
    supplier: 26.9815,
    invoiceDate: 26.9815,
    totalAmount: 'Al',
    netAmount: 'Al',
    actions: 'Al',
  },
  {
    invoiceNumber: 'Silicon',
    customer_name: 'Silicon@gmail.com',
    supplier: 28.0855,
    invoiceDate: 28.0855,
    totalAmount: 'Si',
    netAmount: 'Si',
    actions: 'Si',
  },
  {
    invoiceNumber: 'Phosphorus',
    customer_name: 'Phosphorus@gmail.com',
    supplier: 30.9738,
    invoiceDate: 30.9738,
    totalAmount: 'P',
    netAmount: 'P',
    actions: 'P',
  },
  {
    invoiceNumber: 'Sulfur',
    customer_name: 'Sulfur@gmail.com',
    supplier: 32.065,
    invoiceDate: 32.065,
    totalAmount: 'S',
    netAmount: 'S',
    actions: 'S',
  },
  {
    invoiceNumber: 'Chlorine',
    customer_name: 'Chlorine@gmail.com',
    supplier: 35.453,
    invoiceDate: 35.453,
    totalAmount: 'Cl',
    netAmount: 'Cl',
    actions: 'Cl',
  },
  {
    invoiceNumber: 'Argon',
    customer_name: 'Argon@gmail.com',
    supplier: 39.948,
    invoiceDate: 39.948,
    totalAmount: 'Ar',
    netAmount: 'Ar',
    actions: 'Ar',
  },
  {
    invoiceNumber: 'Potassium',
    customer_name: 'Potassium@gmail.com',
    supplier: 39.0983,
    invoiceDate: 39.0983,
    totalAmount: 'K',
    netAmount: 'K',
    actions: 'K',
  },
  {
    invoiceNumber: 'Calcium',
    customer_name: 'Calcium@gmail.com',
    supplier: 40.078,
    invoiceDate: 40.078,
    totalAmount: 'Ca',
    netAmount: 'Ca',
    actions: 'Ca',
  },
];
