export const CUSTOMERS: any[] = [
  { name: 'Lithium', email: 'Hydrogen@gmail.com', code: 1.0079, actions: 'H' },
  { name: 'Helium', email: 'Helium@gmail.com', code: 4.0026, actions: 'He' },
  { name: 'Liithium', email: 'Liithium@gmail.com', code: 6.941, actions: 'Li' },
  {
    name: 'Beryllium',
    email: 'Beryllium@gmail.com',
    code: 9.0122,
    actions: 'Be',
  },
  { name: 'Boron', email: 'Boron@gmail.com', code: 10.811, actions: 'B' },
  { name: 'Carbon', email: 'Carbon@gmail.com', code: 12.0107, actions: 'C' },
  {
    name: 'Nitrogen',
    email: 'Nitrogen@gmail.com',
    code: 14.0067,
    actions: 'N',
  },
  { name: 'Oxygen', email: 'Oxygen@gmail.com', code: 15.9994, actions: 'O' },
  {
    name: 'Fluorine',
    email: 'Fluorine@gmail.com',
    code: 18.9984,
    actions: 'F',
  },
  { name: 'Neon', email: 'Neon@gmail.com', code: 20.1797, actions: 'Ne' },
  { name: 'Sodium', email: 'Sodium@gmail.com', code: 22.9897, actions: 'Na' },
  {
    name: 'Magnesium',
    email: 'Magnesium@gmail.com',
    code: 24.305,
    actions: 'Mg',
  },
  {
    name: 'Aluminum',
    email: 'Aluminum@gmail.com',
    code: 26.9815,
    actions: 'Al',
  },
  { name: 'Silicon', email: 'Silicon@gmail.com', code: 28.0855, actions: 'Si' },
  {
    name: 'Phosphorus',
    email: 'Phosphorus@gmail.com',
    code: 30.9738,
    actions: 'P',
  },
  { name: 'Sulfur', email: 'Sulfur@gmail.com', code: 32.065, actions: 'S' },
  {
    name: 'Chlorine',
    email: 'Chlorine@gmail.com',
    code: 35.453,
    actions: 'Cl',
  },
  { name: 'Argon', email: 'Argon@gmail.com', code: 39.948, actions: 'Ar' },
  {
    name: 'Potassium',
    email: 'Potassium@gmail.com',
    code: 39.0983,
    actions: 'K',
  },
  { name: 'Calcium', email: 'Calcium@gmail.com', code: 40.078, actions: 'Ca' },
];
export const suppliers: any[] = [
  { name: 'Lithium', email: 'Hydrogen@gmail.com', code: 1.0079, actions: 'H' },
  { name: 'Helium', email: 'Helium@gmail.com', code: 4.0026, actions: 'He' },
  { name: 'Liithium', email: 'Liithium@gmail.com', code: 6.941, actions: 'Li' },
  {
    name: 'Beryllium',
    email: 'Beryllium@gmail.com',
    code: 9.0122,
    actions: 'Be',
  },
  { name: 'Boron', email: 'Boron@gmail.com', code: 10.811, actions: 'B' },
  { name: 'Carbon', email: 'Carbon@gmail.com', code: 12.0107, actions: 'C' },
  {
    name: 'Nitrogen',
    email: 'Nitrogen@gmail.com',
    code: 14.0067,
    actions: 'N',
  },
  { name: 'Oxygen', email: 'Oxygen@gmail.com', code: 15.9994, actions: 'O' },
  {
    name: 'Fluorine',
    email: 'Fluorine@gmail.com',
    code: 18.9984,
    actions: 'F',
  },
  { name: 'Neon', email: 'Neon@gmail.com', code: 20.1797, actions: 'Ne' },
  { name: 'Sodium', email: 'Sodium@gmail.com', code: 22.9897, actions: 'Na' },
  {
    name: 'Magnesium',
    email: 'Magnesium@gmail.com',
    code: 24.305,
    actions: 'Mg',
  },
  {
    name: 'Aluminum',
    email: 'Aluminum@gmail.com',
    code: 26.9815,
    actions: 'Al',
  },
  { name: 'Silicon', email: 'Silicon@gmail.com', code: 28.0855, actions: 'Si' },
  {
    name: 'Phosphorus',
    email: 'Phosphorus@gmail.com',
    code: 30.9738,
    actions: 'P',
  },
  { name: 'Sulfur', email: 'Sulfur@gmail.com', code: 32.065, actions: 'S' },
  {
    name: 'Chlorine',
    email: 'Chlorine@gmail.com',
    code: 35.453,
    actions: 'Cl',
  },
  { name: 'Argon', email: 'Argon@gmail.com', code: 39.948, actions: 'Ar' },
  {
    name: 'Potassium',
    email: 'Potassium@gmail.com',
    code: 39.0983,
    actions: 'K',
  },
  { name: 'Calcium', email: 'Calcium@gmail.com', code: 40.078, actions: 'Ca' },
];
export const itemsCategory: any[] = [
  {
    name: 'Lithium',
    description: 'Hydrogen@gmail.com',
    actions: 'H',
  },
  {
    name: 'Helium',
    description: 'Helium@gmail.com',
    actions: 'He',
  },
  {
    name: 'Liithium',
    description: 'Liithium@gmail.com',
    actions: 'Li',
  },
  {
    name: 'Beryllium',
    description: 'Beryllium@gmail.com',
    actions: 'Be',
  },
  { name: 'Boron', description: 'Boron@gmail.com', actions: 'B' },
  {
    name: 'Carbon',
    description: 'Carbon@gmail.com',
    actions: 'C',
  },
  {
    name: 'Nitrogen',
    description: 'Nitrogen@gmail.com',
    actions: 'N',
  },
  {
    name: 'Oxygen',
    description: 'Oxygen@gmail.com',
    actions: 'O',
  },
  {
    name: 'Fluorine',
    description: 'Fluorine@gmail.com',
    actions: 'F',
  },
  { name: 'Neon', description: 'Neon@gmail.com', code: 20.1797, actions: 'Ne' },
  {
    name: 'Sodium',
    description: 'Sodium@gmail.com',
    actions: 'Na',
  },
  {
    name: 'Magnesium',
    description: 'Magnesium@gmail.com',
    actions: 'Mg',
  },
  {
    name: 'Aluminum',
    description: 'Aluminum@gmail.com',
    actions: 'Al',
  },
  {
    name: 'Silicon',
    description: 'Silicon@gmail.com',
    actions: 'Si',
  },
  {
    name: 'Phosphorus',
    description: 'Phosphorus@gmail.com',
    actions: 'P',
  },
  {
    name: 'Sulfur',
    description: 'Sulfur@gmail.com',
    actions: 'S',
  },
  {
    name: 'Chlorine',
    description: 'Chlorine@gmail.com',
    actions: 'Cl',
  },
  {
    name: 'Argon',
    description: 'Argon@gmail.com',
    actions: 'Ar',
  },
  {
    name: 'Potassium',
    description: 'Potassium@gmail.com',
    actions: 'K',
  },
  { name: 'Calcium', email: 'Calcium@gmail.com', code: 40.078, actions: 'Ca' },
];
export const payments: any[] = [
  {
    name: 'Lithium',
    amount: 'Hydrogen@gmail.com',
    paymentDate: 1.0079,
    description: 1.0079,
    actions: 'H',
  },
  {
    name: 'Helium',
    amount: 'Helium@gmail.com',
    paymentDate: 4.0026,
    description: 4.0026,
    actions: 'He',
  },
  {
    name: 'Liithium',
    amount: 'Liithium@gmail.com',
    paymentDate: 6.941,
    description: 6.941,
    actions: 'Li',
  },
  {
    name: 'Beryllium',
    amount: 'Beryllium@gmail.com',
    paymentDate: 9.0122,
    description: 9.0122,
    actions: 'Be',
  },
  {
    name: 'Boron',
    amount: 'Boron@gmail.com',
    paymentDate: 10.811,
    description: 10.811,
    actions: 'B',
  },
  {
    name: 'Carbon',
    amount: 'Carbon@gmail.com',
    paymentDate: 12.0107,
    description: 12.0107,
    actions: 'C',
  },
  {
    name: 'Nitrogen',
    amount: 'Nitrogen@gmail.com',
    paymentDate: 14.0067,
    description: 14.0067,
    actions: 'N',
  },
  {
    name: 'Oxygen',
    amount: 'Oxygen@gmail.com',
    paymentDate: 15.9994,
    description: 15.9994,
    actions: 'O',
  },
  {
    name: 'Fluorine',
    amount: 'Fluorine@gmail.com',
    paymentDate: 18.9984,
    description: 18.9984,
    actions: 'F',
  },
  {
    name: 'Neon',
    amount: 'Neon@gmail.com',
    paymentDate: 20.1797,
    description: 20.1797,
    actions: 'Ne',
  },
  {
    name: 'Sodium',
    amount: 'Sodium@gmail.com',
    paymentDate: 22.9897,
    description: 22.9897,
    actions: 'Na',
  },
  {
    name: 'Magnesium',
    amount: 'Magnesium@gmail.com',
    paymentDate: 24.305,
    description: 24.305,
    actions: 'Mg',
  },
  {
    name: 'Aluminum',
    amount: 'Aluminum@gmail.com',
    paymentDate: 26.9815,
    description: 26.9815,
    actions: 'Al',
  },
  {
    name: 'Silicon',
    amount: 'Silicon@gmail.com',
    paymentDate: 28.0855,
    description: 28.0855,
    actions: 'Si',
  },
  {
    name: 'Phosphorus',
    amount: 'Phosphorus@gmail.com',
    paymentDate: 30.9738,
    description: 30.9738,
    actions: 'P',
  },
  {
    name: 'Sulfur',
    amount: 'Sulfur@gmail.com',
    paymentDate: 32.065,
    description: 32.065,
    actions: 'S',
  },
  {
    name: 'Chlorine',
    amount: 'Chlorine@gmail.com',
    paymentDate: 35.453,
    description: 35.453,
    actions: 'Cl',
  },
  {
    name: 'Argon',
    amount: 'Argon@gmail.com',
    paymentDate: 39.948,
    description: 39.948,
    actions: 'Ar',
  },
  {
    name: 'Potassium',
    amount: 'Potassium@gmail.com',
    paymentDate: 39.0983,
    description: 39.0983,
    actions: 'K',
  },
  { name: 'Calcium', email: 'Calcium@gmail.com', code: 40.078, actions: 'Ca' },
];
export const expenses: any[] = [
  {
    name: 'Lithium',
    containerNumber: 'Hydrogen@gmail.com',
    amount: 1.0079,
    expenseDate: 1.0079,
    actions: 'H',
  },
  {
    name: 'Helium',
    containerNumber: 'Helium@gmail.com',
    amount: 4.0026,
    expenseDate: 4.0026,
    actions: 'He',
  },
  {
    name: 'Liithium',
    containerNumber: 'Liithium@gmail.com',
    amount: 6.941,
    expenseDate: 6.941,
    actions: 'Li',
  },
  {
    name: 'Beryllium',
    containerNumber: 'Beryllium@gmail.com',
    amount: 9.0122,
    expenseDate: 9.0122,
    actions: 'Be',
  },
  {
    name: 'Boron',
    containerNumber: 'Boron@gmail.com',
    amount: 10.811,
    expenseDate: 10.811,
    actions: 'B',
  },
  {
    name: 'Carbon',
    containerNumber: 'Carbon@gmail.com',
    amount: 12.0107,
    expenseDate: 12.0107,
    actions: 'C',
  },
  {
    name: 'Nitrogen',
    containerNumber: 'Nitrogen@gmail.com',
    amount: 14.0067,
    expenseDate: 14.0067,
    actions: 'N',
  },
  {
    name: 'Oxygen',
    containerNumber: 'Oxygen@gmail.com',
    amount: 15.9994,
    expenseDate: 15.9994,
    actions: 'O',
  },
  {
    name: 'Fluorine',
    containerNumber: 'Fluorine@gmail.com',
    amount: 18.9984,
    expenseDate: 18.9984,
    actions: 'F',
  },
  {
    name: 'Neon',
    containerNumber: 'Neon@gmail.com',
    amount: 20.1797,
    expenseDate: 20.1797,
    actions: 'Ne',
  },
  {
    name: 'Sodium',
    containerNumber: 'Sodium@gmail.com',
    amount: 22.9897,
    expenseDate: 22.9897,
    actions: 'Na',
  },
  {
    name: 'Magnesium',
    containerNumber: 'Magnesium@gmail.com',
    amount: 24.305,
    expenseDate: 24.305,
    actions: 'Mg',
  },
  {
    name: 'Aluminum',
    containerNumber: 'Aluminum@gmail.com',
    amount: 26.9815,
    expenseDate: 26.9815,
    actions: 'Al',
  },
  {
    name: 'Silicon',
    containerNumber: 'Silicon@gmail.com',
    amount: 28.0855,
    expenseDate: 28.0855,
    actions: 'Si',
  },
  {
    name: 'Phosphorus',
    containerNumber: 'Phosphorus@gmail.com',
    amount: 30.9738,
    expenseDate: 30.9738,
    actions: 'P',
  },
  {
    name: 'Sulfur',
    containerNumber: 'Sulfur@gmail.com',
    amount: 32.065,
    expenseDate: 32.065,
    actions: 'S',
  },
  {
    name: 'Chlorine',
    containerNumber: 'Chlorine@gmail.com',
    amount: 35.453,
    expenseDate: 35.453,
    actions: 'Cl',
  },
  {
    name: 'Argon',
    containerNumber: 'Argon@gmail.com',
    amount: 39.948,
    expenseDate: 39.948,
    actions: 'Ar',
  },
  {
    name: 'Potassium',
    containerNumber: 'Potassium@gmail.com',
    amount: 39.0983,
    expenseDate: 39.0983,
    actions: 'K',
  },
  {
    name: 'Calcium',
    containerNumber: 'Calcium@gmail.com',
    amount: 40.078,
    expenseDate: 40.078,
    actions: 'Ca',
  },
];
export const transactions: any[] = [
  {
    name: 'Lithium',
    invoiceNumber: 'Hydrogen@gmail.com',
    supplierName: 'Hydrogen@gmail.com',
    transactionDate: 1.0079,
    actions: 'H',
  },
  {
    name: 'Helium',
    invoiceNumber: 'Helium@gmail.com',
    supplierName: 'Helium@gmail.com',
    transactionDate: 4.0026,
    actions: 'He',
  },
  {
    name: 'Liithium',
    invoiceNumber: 'Liithium@gmail.com',
    supplierName: 'Liithium@gmail.com',
    transactionDate: 6.941,
    actions: 'Li',
  },
  {
    name: 'Beryllium',
    invoiceNumber: 'Beryllium@gmail.com',
    supplierName: 'Beryllium@gmail.com',
    transactionDate: 9.0122,
    actions: 'Be',
  },
  {
    name: 'Boron',
    invoiceNumber: 'Boron@gmail.com',
    supplierName: 'Boron@gmail.com',
    transactionDate: 10.811,
    actions: 'B',
  },
  {
    name: 'Carbon',
    invoiceNumber: 'Carbon@gmail.com',
    supplierName: 'Carbon@gmail.com',
    transactionDate: 12.0107,
    actions: 'C',
  },
  {
    name: 'Nitrogen',
    invoiceNumber: 'Nitrogen@gmail.com',
    supplierName: 'Nitrogen@gmail.com',
    transactionDate: 14.0067,
    actions: 'N',
  },
  {
    name: 'Oxygen',
    invoiceNumber: 'Oxygen@gmail.com',
    supplierName: 'Oxygen@gmail.com',
    transactionDate: 15.9994,
    actions: 'O',
  },
  {
    name: 'Fluorine',
    invoiceNumber: 'Fluorine@gmail.com',
    supplierName: 'Fluorine@gmail.com',
    transactionDate: 18.9984,
    actions: 'F',
  },
  {
    name: 'Neon',
    invoiceNumber: 'Neon@gmail.com',
    supplierName: 'Neon@gmail.com',
    transactionDate: 20.1797,
    actions: 'Ne',
  },
  {
    name: 'Sodium',
    invoiceNumber: 'Sodium@gmail.com',
    supplierName: 'Sodium@gmail.com',
    transactionDate: 22.9897,
    actions: 'Na',
  },
  {
    name: 'Magnesium',
    invoiceNumber: 'Magnesium@gmail.com',
    supplierName: 'Magnesium@gmail.com',
    transactionDate: 24.305,
    actions: 'Mg',
  },
  {
    name: 'Aluminum',
    invoiceNumber: 'Aluminum@gmail.com',
    supplierName: 'Aluminum@gmail.com',
    transactionDate: 26.9815,
    actions: 'Al',
  },
  {
    name: 'Silicon',
    invoiceNumber: 'Silicon@gmail.com',
    supplierName: 'Silicon@gmail.com',
    transactionDate: 28.0855,
    actions: 'Si',
  },
  {
    name: 'Phosphorus',
    invoiceNumber: 'Phosphorus@gmail.com',
    supplierName: 'Phosphorus@gmail.com',
    transactionDate: 30.9738,
    actions: 'P',
  },
  {
    name: 'Sulfur',
    invoiceNumber: 'Sulfur@gmail.com',
    supplierName: 'Sulfur@gmail.com',
    transactionDate: 32.065,
    actions: 'S',
  },
  {
    name: 'Chlorine',
    invoiceNumber: 'Chlorine@gmail.com',
    supplierName: 'Chlorine@gmail.com',
    transactionDate: 35.453,
    actions: 'Cl',
  },
  {
    name: 'Argon',
    invoiceNumber: 'Argon@gmail.com',
    supplierName: 'Argon@gmail.com',
    transactionDate: 39.948,
    actions: 'Ar',
  },
  {
    name: 'Potassium',
    invoiceNumber: 'Potassium@gmail.com',
    supplierName: 'Potassium@gmail.com',
    transactionDate: 39.0983,
    actions: 'K',
  },
  {
    name: 'Calcium',
    invoiceNumber: 'Calcium@gmail.com',
    supplierName: 'Calcium@gmail.com',
    transactionDate: 40.078,
    actions: 'Ca',
  },
];
export const shippingData: any[] = [
  {
    name: 'Lithium',
    containerNumber: 'Hydrogen@gmail.com',
    contatierSequance: 1.0079,
    ShippingDate: 1.0079,
    actions: 'H',
  },
  {
    name: 'Helium',
    containerNumber: 'Helium@gmail.com',
    contatierSequance: 4.0026,
    ShippingDate: 4.0026,
    actions: 'He',
  },
  {
    name: 'Liithium',
    containerNumber: 'Liithium@gmail.com',
    contatierSequance: 6.941,
    ShippingDate: 6.941,
    actions: 'Li',
  },
  {
    name: 'Beryllium',
    containerNumber: 'Beryllium@gmail.com',
    contatierSequance: 9.0122,
    ShippingDate: 9.0122,
    actions: 'Be',
  },
  {
    name: 'Boron',
    containerNumber: 'Boron@gmail.com',
    contatierSequance: 10.811,
    ShippingDate: 10.811,
    actions: 'B',
  },
  {
    name: 'Carbon',
    containerNumber: 'Carbon@gmail.com',
    contatierSequance: 12.0107,
    ShippingDate: 12.0107,
    actions: 'C',
  },
  {
    name: 'Nitrogen',
    containerNumber: 'Nitrogen@gmail.com',
    contatierSequance: 14.0067,
    ShippingDate: 14.0067,
    actions: 'N',
  },
  {
    name: 'Oxygen',
    containerNumber: 'Oxygen@gmail.com',
    contatierSequance: 15.9994,
    ShippingDate: 15.9994,
    actions: 'O',
  },
  {
    name: 'Fluorine',
    containerNumber: 'Fluorine@gmail.com',
    contatierSequance: 18.9984,
    ShippingDate: 18.9984,
    actions: 'F',
  },
  {
    name: 'Neon',
    containerNumber: 'Neon@gmail.com',
    contatierSequance: 20.1797,
    ShippingDate: 20.1797,
    actions: 'Ne',
  },
  {
    name: 'Sodium',
    containerNumber: 'Sodium@gmail.com',
    contatierSequance: 22.9897,
    ShippingDate: 22.9897,
    actions: 'Na',
  },
  {
    name: 'Magnesium',
    containerNumber: 'Magnesium@gmail.com',
    contatierSequance: 24.305,
    ShippingDate: 24.305,
    actions: 'Mg',
  },
  {
    name: 'Aluminum',
    containerNumber: 'Aluminum@gmail.com',
    contatierSequance: 26.9815,
    ShippingDate: 26.9815,
    actions: 'Al',
  },
  {
    name: 'Silicon',
    containerNumber: 'Silicon@gmail.com',
    contatierSequance: 28.0855,
    ShippingDate: 28.0855,
    actions: 'Si',
  },
  {
    name: 'Phosphorus',
    containerNumber: 'Phosphorus@gmail.com',
    contatierSequance: 30.9738,
    ShippingDate: 30.9738,
    actions: 'P',
  },
  {
    name: 'Sulfur',
    containerNumber: 'Sulfur@gmail.com',
    contatierSequance: 32.065,
    ShippingDate: 32.065,
    actions: 'S',
  },
  {
    name: 'Chlorine',
    containerNumber: 'Chlorine@gmail.com',
    contatierSequance: 35.453,
    ShippingDate: 35.453,
    actions: 'Cl',
  },
  {
    name: 'Argon',
    containerNumber: 'Argon@gmail.com',
    contatierSequance: 39.948,
    ShippingDate: 39.948,
    actions: 'Ar',
  },
  {
    name: 'Potassium',
    containerNumber: 'Potassium@gmail.com',
    contatierSequance: 39.0983,
    ShippingDate: 39.0983,
    actions: 'K',
  },
  {
    name: 'Calcium',
    containerNumber: 'Calcium@gmail.com',
    contatierSequance: 40.078,
    ShippingDate: 40.078,
    actions: 'Ca',
  },
];
